# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  SOLUTION_FILE_PATH: ./anime-download-episodes.sln
  VCPKG_X64_INCLUDES: C:/vcpkg/installed/x64-windows/include
  VCPKG_X64_LIBS: C:/vcpkg/installed/x64-windows/lib
  VCPKG_X86_INCLUDES: C:/vcpkg/installed/x86-windows/include
  VCPKG_X86_LIBS: C:/vcpkg/installed/x86-windows/lib

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    #- name: Restore NuGet packages
    #  working-directory: ${{env.GITHUB_WORKSPACE}}
    #  run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Install Vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh
        vcpkg integrate install
    
    - name: Install dependencies
      run: |
        vcpkg install sqlite3:x86-windows sqlite3:x64-windows curl:x86-windows curl:x64-windows nlohmann-json:x86-windows nlohmann-json:x64-windows
        cd ..

    - name: Build Debug Win32
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Debug /p:Plataform=Win32 ${{env.SOLUTION_FILE_PATH}}

    - name: Build Debug x64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Debug /p:Plataform=x64 ${{env.SOLUTION_FILE_PATH}}
      
    - name: Build Release Win32
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Release /p:Plataform=Win32 ${{env.SOLUTION_FILE_PATH}}
      
    - name: Build Release x64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Release /p:Plataform=x64 ${{env.SOLUTION_FILE_PATH}}
